"""PR node: commit the worktree's diff, push the feature branch, and
open a pull request via gh CLI.

No Claude call here — pure bash. The PR body is assembled from the
state we already have (intake + plan + code_summary + verify report).
"""

from __future__ import annotations

import json
import logging
import subprocess
from pathlib import Path

from claude_pipeline.state import PipelineState

log = logging.getLogger(__name__)

CO_AUTHOR_TRAILER = "Co-Authored-By: claude-pipeline <noreply@anthropic.com>"


def _git(cwd: str, *args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if check and proc.returncode != 0:
        raise RuntimeError(
            f"git {' '.join(args)} failed (exit {proc.returncode}): {proc.stderr.strip()}"
        )
    return proc.stdout.strip()


def _build_pr_body(state: PipelineState) -> str:
    intake = state.get("intake", {})
    verify = state.get("verify", {})
    plan = state.get("plan", [])

    lines = [
        f"Closes #{state['issue_number']}.",
        "",
        "## Summary",
        "",
        state.get("code_summary", "(no summary captured)"),
        "",
        "## Intake decisions",
        "",
        f"- **Task type:** `{intake.get('task_type', '?')}`",
        f"- **Tier:** {intake.get('complexity_tier', '?')}",
        f"- **Right thing:** {intake.get('right_thing_answer', '?')}",
        f"- **Risk flags:** {', '.join(intake.get('risk_flags', [])) or '(none)'}",
        "",
        "## Stages executed",
        "",
    ]
    for i, s in enumerate(plan):
        lines.append(f"{i + 1}. **{s.get('name', '?')}** — {s.get('description', '')}")
    lines.extend(
        [
            "",
            "## Verification",
            "",
            f"- **Passed:** {verify.get('passed', False)}",
            f"- **Summary:** {verify.get('summary', '(no verify summary)')}",
        ]
    )
    if verify.get("failing_tests"):
        lines.append("- **Failing tests:** " + ", ".join(verify["failing_tests"]))
    lines.extend(
        [
            "",
            "---",
            "",
            f"Generated by claude-pipeline run `{state.get('run_id', '?')}`.",
            "",
            CO_AUTHOR_TRAILER,
        ]
    )
    return "\n".join(lines)


def _build_commit_message(state: PipelineState) -> str:
    return (
        f"{state.get('issue_title', 'pipeline run')}\n\n"
        f"Closes #{state['issue_number']}.\n\n"
        f"Generated by claude-pipeline run {state.get('run_id', '?')}.\n\n"
        f"{CO_AUTHOR_TRAILER}"
    )


def pr_node(state: PipelineState) -> dict:
    cwd = state["worktree_path"]
    branch = state["feature_branch"]
    repo = state["repo"]

    # Stage everything that changed, commit, push
    _git(cwd, "add", "-A")
    status = _git(cwd, "status", "--porcelain")
    if not status:
        log.warning("pr: no changes staged — skipping commit/push, no PR")
        return {"error": "pr: nothing to commit"}

    commit_msg = _build_commit_message(state)
    _git(cwd, "commit", "-m", commit_msg)
    log.info("pr: commit created on branch %s", branch)

    _git(cwd, "push", "-u", "origin", branch)
    log.info("pr: branch pushed")

    # Open the PR
    pr_body = _build_pr_body(state)
    title = state.get("issue_title", f"Pipeline run for issue #{state['issue_number']}")
    proc = subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--repo",
            repo,
            "--base",
            state["base_branch"],
            "--head",
            branch,
            "--title",
            title,
            "--body",
            pr_body,
        ],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if proc.returncode != 0:
        return {"error": f"gh pr create failed: {proc.stderr.strip()}"}

    pr_url = proc.stdout.strip()
    # gh prints the PR URL like https://github.com/owner/repo/pull/123
    pr_number = 0
    if "/pull/" in pr_url:
        try:
            pr_number = int(pr_url.rsplit("/", 1)[-1])
        except ValueError:
            pr_number = 0

    log.info("pr created: %s", pr_url)
    return {"pr_url": pr_url, "pr_number": pr_number, "error": None}
